/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LotsIdRouteImport } from './routes/lots/$id'
import { Route as MeetupsIndexRouteImport } from './routes/meetups/index'
import { Route as MeetupsIdRouteImport } from './routes/meetups/$id'
import { Route as OpOnboardingRouteImport } from './routes/op/onboarding'
import { Route as OpScheduleRouteImport } from './routes/op/schedule'
import { Route as OpTodayRouteImport } from './routes/op/today'
import { Route as OpTruckRouteImport } from './routes/op/truck'
import { Route as TrucksIdRouteImport } from './routes/trucks/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OpMeetupsIndexRouteImport } from './routes/op/meetups/index'
import { Route as OpMeetupsNewRouteImport } from './routes/op/meetups/new'
import { Route as OpStopsIdRouteImport } from './routes/op/stops/$id'
import { Route as OpStopsNewRouteImport } from './routes/op/stops/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsIdRoute = LotsIdRouteImport.update({
  id: '/lots/$id',
  path: '/lots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetupsIndexRoute = MeetupsIndexRouteImport.update({
  id: '/meetups/',
  path: '/meetups/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetupsIdRoute = MeetupsIdRouteImport.update({
  id: '/meetups/$id',
  path: '/meetups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpOnboardingRoute = OpOnboardingRouteImport.update({
  id: '/op/onboarding',
  path: '/op/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpScheduleRoute = OpScheduleRouteImport.update({
  id: '/op/schedule',
  path: '/op/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OpTodayRoute = OpTodayRouteImport.update({
  id: '/op/today',
  path: '/op/today',
  getParentRoute: () => rootRouteImport,
} as any)
const OpTruckRoute = OpTruckRouteImport.update({
  id: '/op/truck',
  path: '/op/truck',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIdRoute = TrucksIdRouteImport.update({
  id: '/trucks/$id',
  path: '/trucks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OpMeetupsIndexRoute = OpMeetupsIndexRouteImport.update({
  id: '/op/meetups/',
  path: '/op/meetups/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpMeetupsNewRoute = OpMeetupsNewRouteImport.update({
  id: '/op/meetups/new',
  path: '/op/meetups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OpStopsIdRoute = OpStopsIdRouteImport.update({
  id: '/op/stops/$id',
  path: '/op/stops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpStopsNewRoute = OpStopsNewRouteImport.update({
  id: '/op/stops/new',
  path: '/op/stops/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/lots/$id': typeof LotsIdRoute
  '/meetups/$id': typeof MeetupsIdRoute
  '/op/onboarding': typeof OpOnboardingRoute
  '/op/schedule': typeof OpScheduleRoute
  '/op/today': typeof OpTodayRoute
  '/op/truck': typeof OpTruckRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/meetups/': typeof MeetupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/op/meetups/new': typeof OpMeetupsNewRoute
  '/op/stops/$id': typeof OpStopsIdRoute
  '/op/stops/new': typeof OpStopsNewRoute
  '/op/meetups/': typeof OpMeetupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/lots/$id': typeof LotsIdRoute
  '/meetups/$id': typeof MeetupsIdRoute
  '/op/onboarding': typeof OpOnboardingRoute
  '/op/schedule': typeof OpScheduleRoute
  '/op/today': typeof OpTodayRoute
  '/op/truck': typeof OpTruckRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/meetups': typeof MeetupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/op/meetups/new': typeof OpMeetupsNewRoute
  '/op/stops/$id': typeof OpStopsIdRoute
  '/op/stops/new': typeof OpStopsNewRoute
  '/op/meetups': typeof OpMeetupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/lots/$id': typeof LotsIdRoute
  '/meetups/$id': typeof MeetupsIdRoute
  '/op/onboarding': typeof OpOnboardingRoute
  '/op/schedule': typeof OpScheduleRoute
  '/op/today': typeof OpTodayRoute
  '/op/truck': typeof OpTruckRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/meetups/': typeof MeetupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/op/meetups/new': typeof OpMeetupsNewRoute
  '/op/stops/$id': typeof OpStopsIdRoute
  '/op/stops/new': typeof OpStopsNewRoute
  '/op/meetups/': typeof OpMeetupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/list'
    | '/login'
    | '/map'
    | '/signup'
    | '/lots/$id'
    | '/meetups/$id'
    | '/op/onboarding'
    | '/op/schedule'
    | '/op/today'
    | '/op/truck'
    | '/trucks/$id'
    | '/meetups/'
    | '/api/auth/$'
    | '/op/meetups/new'
    | '/op/stops/$id'
    | '/op/stops/new'
    | '/op/meetups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/list'
    | '/login'
    | '/map'
    | '/signup'
    | '/lots/$id'
    | '/meetups/$id'
    | '/op/onboarding'
    | '/op/schedule'
    | '/op/today'
    | '/op/truck'
    | '/trucks/$id'
    | '/meetups'
    | '/api/auth/$'
    | '/op/meetups/new'
    | '/op/stops/$id'
    | '/op/stops/new'
    | '/op/meetups'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/list'
    | '/login'
    | '/map'
    | '/signup'
    | '/lots/$id'
    | '/meetups/$id'
    | '/op/onboarding'
    | '/op/schedule'
    | '/op/today'
    | '/op/truck'
    | '/trucks/$id'
    | '/meetups/'
    | '/api/auth/$'
    | '/op/meetups/new'
    | '/op/stops/$id'
    | '/op/stops/new'
    | '/op/meetups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SignupRoute: typeof SignupRoute
  LotsIdRoute: typeof LotsIdRoute
  MeetupsIdRoute: typeof MeetupsIdRoute
  OpOnboardingRoute: typeof OpOnboardingRoute
  OpScheduleRoute: typeof OpScheduleRoute
  OpTodayRoute: typeof OpTodayRoute
  OpTruckRoute: typeof OpTruckRoute
  TrucksIdRoute: typeof TrucksIdRoute
  MeetupsIndexRoute: typeof MeetupsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OpMeetupsNewRoute: typeof OpMeetupsNewRoute
  OpStopsIdRoute: typeof OpStopsIdRoute
  OpStopsNewRoute: typeof OpStopsNewRoute
  OpMeetupsIndexRoute: typeof OpMeetupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$id': {
      id: '/lots/$id'
      path: '/lots/$id'
      fullPath: '/lots/$id'
      preLoaderRoute: typeof LotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetups/': {
      id: '/meetups/'
      path: '/meetups'
      fullPath: '/meetups/'
      preLoaderRoute: typeof MeetupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetups/$id': {
      id: '/meetups/$id'
      path: '/meetups/$id'
      fullPath: '/meetups/$id'
      preLoaderRoute: typeof MeetupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/onboarding': {
      id: '/op/onboarding'
      path: '/op/onboarding'
      fullPath: '/op/onboarding'
      preLoaderRoute: typeof OpOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/schedule': {
      id: '/op/schedule'
      path: '/op/schedule'
      fullPath: '/op/schedule'
      preLoaderRoute: typeof OpScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/today': {
      id: '/op/today'
      path: '/op/today'
      fullPath: '/op/today'
      preLoaderRoute: typeof OpTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/truck': {
      id: '/op/truck'
      path: '/op/truck'
      fullPath: '/op/truck'
      preLoaderRoute: typeof OpTruckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/$id': {
      id: '/trucks/$id'
      path: '/trucks/$id'
      fullPath: '/trucks/$id'
      preLoaderRoute: typeof TrucksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/meetups/': {
      id: '/op/meetups/'
      path: '/op/meetups'
      fullPath: '/op/meetups/'
      preLoaderRoute: typeof OpMeetupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/meetups/new': {
      id: '/op/meetups/new'
      path: '/op/meetups/new'
      fullPath: '/op/meetups/new'
      preLoaderRoute: typeof OpMeetupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/stops/$id': {
      id: '/op/stops/$id'
      path: '/op/stops/$id'
      fullPath: '/op/stops/$id'
      preLoaderRoute: typeof OpStopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op/stops/new': {
      id: '/op/stops/new'
      path: '/op/stops/new'
      fullPath: '/op/stops/new'
      preLoaderRoute: typeof OpStopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SignupRoute: SignupRoute,
  LotsIdRoute: LotsIdRoute,
  MeetupsIdRoute: MeetupsIdRoute,
  OpOnboardingRoute: OpOnboardingRoute,
  OpScheduleRoute: OpScheduleRoute,
  OpTodayRoute: OpTodayRoute,
  OpTruckRoute: OpTruckRoute,
  TrucksIdRoute: TrucksIdRoute,
  MeetupsIndexRoute: MeetupsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OpMeetupsNewRoute: OpMeetupsNewRoute,
  OpStopsIdRoute: OpStopsIdRoute,
  OpStopsNewRoute: OpStopsNewRoute,
  OpMeetupsIndexRoute: OpMeetupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
